
[programs.localnet]
webstreet_core = "WEB11111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[scripts]
test = "anchor test"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/webstreet_core"]
