
[package]
name = "webstreet_core"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.29.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "webstreet_core"

[features]
no-entrypoint = []
